### ISSUE TITLE
Doesn't work with the latest  version of Nova (2.0.9)

### ISSUE THREAD

**Issue by denmette** [emiliogrv/nova-batch-load#1]
I got a problem with the nova version 2.0.9

`vendor.js?id=eaffe66c3a2800ae7df2:1 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at p.init (https://baropkamp.test/nova-api/scripts/batch-load-field:1:228977)
    at Array.<anonymous> (https://baropkamp.test/vendor/nova/vendor.js?id=eaffe66c3a2800ae7df2:1:1728575)
    at Gt (https://baropkamp.test/vendor/nova/vendor.js?id=eaffe66c3a2800ae7df2:1:1728020)
It @ vendor.js?id=eaffe66c3a2800ae7df2:1
jt @ vendor.js?id=eaffe66c3a2800ae7df2:1
Yt @ vendor.js?id=eaffe66c3a2800ae7df2:1
(anonymous) @ vendor.js?id=eaffe66c3a2800ae7df2:1
Gt @ vendor.js?id=eaffe66c3a2800ae7df2:1
Promise.then (async)
Vt @ vendor.js?id=eaffe66c3a2800ae7df2:1
ee @ vendor.js?id=eaffe66c3a2800ae7df2:1
t.$nextTick @ vendor.js?id=eaffe66c3a2800ae7df2:1
mounted @ app.js?id=af7f60e144c36d0eb627:1
Pt @ vendor.js?id=eaffe66c3a2800ae7df2:1
en @ vendor.js?id=eaffe66c3a2800ae7df2:1
insert @ vendor.js?id=eaffe66c3a2800ae7df2:1
y @ vendor.js?id=eaffe66c3a2800ae7df2:1
(anonymous) @ vendor.js?id=eaffe66c3a2800ae7df2:1
t._update @ vendor.js?id=eaffe66c3a2800ae7df2:1
ln.before @ vendor.js?id=eaffe66c3a2800ae7df2:1
ln.get @ vendor.js?id=eaffe66c3a2800ae7df2:1
ln.run @ vendor.js?id=eaffe66c3a2800ae7df2:1
un @ vendor.js?id=eaffe66c3a2800ae7df2:1
(anonymous) @ vendor.js?id=eaffe66c3a2800ae7df2:1
Gt @ vendor.js?id=eaffe66c3a2800ae7df2:1
Promise.then (async)
Vt @ vendor.js?id=eaffe66c3a2800ae7df2:1
ee @ vendor.js?id=eaffe66c3a2800ae7df2:1
(anonymous) @ vendor.js?id=eaffe66c3a2800ae7df2:1
ln.update @ vendor.js?id=eaffe66c3a2800ae7df2:1
Mt.notify @ vendor.js?id=eaffe66c3a2800ae7df2:1
set @ vendor.js?id=eaffe66c3a2800ae7df2:1
On.dn.set @ vendor.js?id=eaffe66c3a2800ae7df2:1
(anonymous) @ app.js?id=af7f60e144c36d0eb627:1
y @ app.js?id=af7f60e144c36d0eb627:1
(anonymous) @ app.js?id=af7f60e144c36d0eb627:1
e.<computed> @ app.js?id=af7f60e144c36d0eb627:1
o @ app.js?id=af7f60e144c36d0eb627:1
(anonymous) @ app.js?id=af7f60e144c36d0eb627:1
Promise.then (async)
o @ app.js?id=af7f60e144c36d0eb627:1
(anonymous) @ app.js?id=af7f60e144c36d0eb627:1
t @ app.js?id=af7f60e144c36d0eb627:1
(anonymous) @ app.js?id=af7f60e144c36d0eb627:1
(anonymous) @ app.js?id=af7f60e144c36d0eb627:1
(anonymous) @ app.js?id=af7f60e144c36d0eb627:1
y @ app.js?id=af7f60e144c36d0eb627:1
(anonymous) @ app.js?id=af7f60e144c36d0eb627:1
e.<computed> @ app.js?id=af7f60e144c36d0eb627:1
o @ app.js?id=af7f60e144c36d0eb627:1
(anonymous) @ app.js?id=af7f60e144c36d0eb627:1
t @ app.js?id=af7f60e144c36d0eb627:1
(anonymous) @ app.js?id=af7f60e144c36d0eb627:1
(anonymous) @ app.js?id=af7f60e144c36d0eb627:1
Pt @ vendor.js?id=eaffe66c3a2800ae7df2:1
en @ vendor.js?id=eaffe66c3a2800ae7df2:1
vn._init @ vendor.js?id=eaffe66c3a2800ae7df2:1
p @ vendor.js?id=eaffe66c3a2800ae7df2:1
(anonymous) @ vendor.js?id=eaffe66c3a2800ae7df2:1
init @ vendor.js?id=eaffe66c3a2800ae7df2:1
n @ vendor.js?id=eaffe66c3a2800ae7df2:1
(anonymous) @ vendor.js?id=eaffe66c3a2800ae7df2:1
M @ vendor.js?id=eaffe66c3a2800ae7df2:1
(anonymous) @ vendor.js?id=eaffe66c3a2800ae7df2:1
t._update @ vendor.js?id=eaffe66c3a2800ae7df2:1
ln.before @ vendor.js?id=eaffe66c3a2800ae7df2:1
ln.get @ vendor.js?id=eaffe66c3a2800ae7df2:1
ln.run @ vendor.js?id=eaffe66c3a2800ae7df2:1
un @ vendor.js?id=eaffe66c3a2800ae7df2:1
(anonymous) @ vendor.js?id=eaffe66c3a2800ae7df2:1
Gt @ vendor.js?id=eaffe66c3a2800ae7df2:1
Promise.then (async)
Vt @ vendor.js?id=eaffe66c3a2800ae7df2:1
ee @ vendor.js?id=eaffe66c3a2800ae7df2:1
t.$nextTick @ vendor.js?id=eaffe66c3a2800ae7df2:1
(anonymous) @ app.js?id=af7f60e144c36d0eb627:1
y @ app.js?id=af7f60e144c36d0eb627:1
(anonymous) @ app.js?id=af7f60e144c36d0eb627:1
e.<computed> @ app.js?id=af7f60e144c36d0eb627:1
o @ app.js?id=af7f60e144c36d0eb627:1
(anonymous) @ app.js?id=af7f60e144c36d0eb627:1
Promise.then (async)
o @ app.js?id=af7f60e144c36d0eb627:1
(anonymous) @ app.js?id=af7f60e144c36d0eb627:1
t @ app.js?id=af7f60e144c36d0eb627:1
(anonymous) @ app.js?id=af7f60e144c36d0eb627:1
l @ app.js?id=af7f60e144c36d0eb627:1
z @ vendor.js?id=eaffe66c3a2800ae7df2:1
o @ vendor.js?id=eaffe66c3a2800ae7df2:1
lt @ vendor.js?id=eaffe66c3a2800ae7df2:1
qt.confirmTransition @ vendor.js?id=eaffe66c3a2800ae7df2:1
qt.transitionTo @ vendor.js?id=eaffe66c3a2800ae7df2:1
xt.init @ vendor.js?id=eaffe66c3a2800ae7df2:1
beforeCreate @ vendor.js?id=eaffe66c3a2800ae7df2:1
Pt @ vendor.js?id=eaffe66c3a2800ae7df2:1
en @ vendor.js?id=eaffe66c3a2800ae7df2:1
vn._init @ vendor.js?id=eaffe66c3a2800ae7df2:1
vn @ vendor.js?id=eaffe66c3a2800ae7df2:1
value @ app.js?id=af7f60e144c36d0eb627:1
(anonymous) @ new?viaResource=&viaResourceId=&viaRelationship=:213
batch-load-field:1 Uncaught (in promise) TypeError: t.data.filter is not a function
    at p.<anonymous> (batch-load-field:1)
    at E (batch-load-field:1)
    at Generator._invoke (batch-load-field:1)
    at Generator.e.<computed> [as next] (batch-load-field:1)
    at n (batch-load-field:1)
    at batch-load-field:1`

**Comment by denmette** [comment]
I was trying to fix the problem myself, but I didn't succeed to make the plugin work ...

**Comment by emiliogrv** [comment]
Hi, @DenMette solved, enjoy!

**Comment by denmette** [comment]
Thanks!

**Comment by Milkhan** [comment]
@emiliogrv Can you please adapt it to Nova 3.x please?
